### ISSUE TITLE
[Feature]: Add suffix to git tags to support mono-repos

### ISSUE THREAD

**Issue by canidam** [gembaadvantage/uplift#297]
### Describe your feature

I've a use-case where I manage multiple artifacts in a mono-repo.
The uplift flows works well for versioning each in my CI. But the git tag step has a problem: since I manage multiple artifacts in the same repo, this will collide, for example two modules with v0.1.0 are released at different times.

The first release will tag commit A, then later on when the second artifact is released the same tag will move to commit B.

What I used to do is prefix my tags with the module name, e.g `mymodule-v0.1.0`.

### Your potential solution

An optional solution can be a new config parameter:
```yaml
git:
  usePrefix: true
```

Then, provide the prefix for this release either from the version file or using an environment variable (UPLIFT_TAG_PREFIX).

### Any additional information?

This should be fairly simple; if accepted, I can open a PR for this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by purpleclay** [comment]
:wave: @canidam, thanks for raising an issue against uplift. I'll read your proposal later today and respond.

**Comment by ga-paul-t** [comment]
👋 @canidam, thanks for raising an issue against uplift. I'll read your proposal later today and respond.

**Comment by ga-paul-t** [comment]
Yes, you are right. Uplift is strongly tied to semantic versioning and only currently supports using a `v` prefix, which is baked into the internal git methods. Using a suffix is an option. But if that suffix has greater meaning than just `alpha` and `beta` (_for example_), it would require some filtering to ensure it retrieved tags for a specific component of your mono-repo.

Technically prefixing a tag with `v` is not a valid semantic version, but `uplift` treats this as a special case since it is widely used. And avoiding any other types of prefixes will ensure your repositories remain compatible with other semantic versioning tooling.

Can I ask how you are using `uplift` within your mono-repo? I haven't worked on a mono-repo in a long time. Are you versioning all components with the same semver? Or do you ever version components individually within the same mono-repo?

Just thinking out loud and wondering if that is a scenario that needs investigating outside of this issue

**Comment by ga-paul-t** [comment]
Awesome. I will take a look in the morning first thing.

**Comment by ga-paul-t** [comment]
> I also have a mono-repo with multiple services (which they share common libs). But I'm not planning to use uplift there, it is much more complicated (for now).

Would you mind describing how you solve semantic versioning currently for such a scenario? I am planning to expand `uplift` this year to better support prerelease workflows. And mono-repos is definitely another type of workflow that I would like to start thinking about more.

**Comment by canidam** [comment]
Sure. 
As we don't have solution for that, we don't really use semver. Each service has its own build process, and the version is based on the build number. This works for us because the release cadence is frequent, and dependencies between services are released together. Using semver would probably be a better strategy.

**Comment by canidam** [comment]
I realize now there is another feature required for this to work. Since CHANGELOG captures all commits since CurrentVersion to NextVersion, there will be irrelevant commits for a specific service.

```
* ecf839d fix(serviceA): some changes to A
* 239c4b7 feat(serviceB): some changes to B
```

This log will cause major bump when releasing service A, thought it's not related.
Currently uplift provides exclude for changelogs. To support this workflow, an _include_ option is necessary. 
I imagine a workflow such as

`uplift release --prerelease <serviceName> --include <serviceName>,[additional patterns]`
Which will consider just commits with the included patterns.

It add additional requirements for mono-repos (you have to use both `--prerelease X --include X`) but I tell you - there is nothing in the open source that supports this today, and this doesn't break the SemVer semantics (it does use the `prerelease` in a hacky way)

**Comment by ga-paul-t** [comment]
It does feel like there are two distinct features here:

1. The ability to filter on a prerelease when calculating the next semantic version (which is where this issue is heading)
2. The ability to filter git log to only include a subset of commits based on a regex match, i.e. the inverse of `--exclude`. This would be surfaced through changelog creation (I am going to raise another issue for this)

I agree this does add additional requirements for mono-repos, but mono-repos come with added complexity when it comes to versioning.

**Comment by canidam** [comment]
> I agree this does add additional requirements for mono-repos, but mono-repos come with added complexity when it comes to versioning.

I agree. If uplift will provide such functionality, it can be useful for any mono-repo. Just needs to be documented with some examples.
